                                  # Intialization 
kind: Deployment
apiVersion: apps/v1

                                  # Metadata (About Deploymnet)
metadata:
  name: try-deployment
  labels:
    app: nginx

                                  # Creation Flow --> Specs of replicas --> template of pods --> Containers 


spec:                             # Of Replicas 
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:                       # Of pods 
    metadata:                     # About Pods (The only thing pods need is Labeled containers)
      labels:                     # We only need these labeled container in our pods
        app: nginx
    spec:                         # Of Conatiner
     containers: 
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

                                  # RUN COMMAND: kubectl apply -f Deployment.yaml

