# Intialization 
kind: Deployment
apiVersion: apps/v1

# Metadata (About Deploymnet)
metadata:
  name: try-deployment
  labels:
    app: nginx

# specs of the Replicas and container
spec: # Of Replicas 
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: # Of Conatiner
     containers: 
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

# RUN COMMAND: kubectl apply -f Deployment.yaml

